name: Deploy Docker Backend

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  # TRABAJO 1: Crear Infraestructura con Terraform
  infrastructure:
    name: Terraform & Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    
    # Exportamos outputs de Terraform para usarlos en el siguiente paso
    outputs:
      acr_server: ${{ steps.tf_output.outputs.acr_server }}
      acr_name: ${{ steps.tf_output.outputs.acr_name }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      # Extraemos los datos del ACR que Terraform acaba de crear
      - name: Get Terraform Outputs
        id: tf_output
        run: |
          echo "acr_server=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "acr_name=$(terraform output -raw acr_name)" >> $GITHUB_OUTPUT

  # TRABAJO 2: Construir Docker y Desplegar
  build-and-deploy:
    needs: infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - uses: actions/checkout@v4
      
      # 1. Login en Azure (General)
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2. Login en el ACR (Usando el nombre que nos dio Terraform)
      - name: Login to ACR
        run: az acr login --name ${{ needs.infrastructure.outputs.acr_name }}

      # 3. Construir imagen y subirla
      - name: Build and Push Docker Image
        env:
          ACR_SERVER: ${{ needs.infrastructure.outputs.acr_server }}
          IMAGE_NAME: testing-backend
        run: |
          docker build -t $ACR_SERVER/$IMAGE_NAME:latest .
          docker push $ACR_SERVER/$IMAGE_NAME:latest

      # 4. Avisar al App Service de que hay imagen nueva
      - name: Update Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'terraform-docker-deploy-test-jsm' # <--- Â¡PON EL MISMO NOMBRE QUE EN MAIN.TF!
          images: '${{ needs.infrastructure.outputs.acr_server }}/testing-backend:latest'